%% STEP10_FINAL_ARTICLE1_MATCHED_WINDOWS_N22.m
% Final Article2 spectral re-analysis aligned to the revised Article1 task-period windows.
%
% IMPORTANT
% ---------
% This version does NOT require an EEG_clean folder.
% It uses:
%   1) STEP09A2_MergedTrialPhaseTable.csv
%   2) raw task MAT files under the IPM/Subjects archive
%   3) TaskEEG_ChannelBand_SubjectFeatures_FINAL.csv only to recover/verify
%      the final N=22 subject set.
%
% One fixed preprocessing/extraction path is used. No extraction-mode
% selection is performed from the statistical results.
%
% FINAL PRIMARY TASK-PERIOD WINDOWS (matched to revised Article1):
%   stimulus / early encoding: 0 to 0.6 s from stimulus onset
%   maintenance             : 0 to 1.0 s from maintenance onset
%   retrieval               : 0 to 0.6 s from retrieval onset
% The pre-event interval is NOT included in spectral feature calculation.
%
% DIRECT PHASE SENSITIVITY BRANCH:
%   stimulus, maintenance, retrieval: identical 0 to 0.6 s post-onset windows
% This branch is used only for direct cross-phase condition-effect magnitude
% comparisons so that unequal primary window lengths do not bias that test.
%
% MATLAB R2021a compatible.
%
% Main outputs:
%   STEP10A_Article1Matched_SubjectChannelFeatures_N22.csv
%   STEP10A_Article1Matched_SubjectROIFeatures_N22.csv
%   STEP10B_Article1Matched_Channel_Omnibus.csv
%   STEP10B_Article1Matched_ROI_Omnibus.csv
%   STEP10S_Equal0600_Channel_Omnibus.csv
%   STEP10S_Equal0600_ROI_Omnibus.csv
%   STEP10S_FocusedIndices_DirectPhase_Omnibus.csv
%   STEP10D_ERP_DirectPhase_Omnibus.csv
%   STEP10E_DirectPhase_SupportSummary.csv
%   STEP10E_ManuscriptDecisionSummary.csv
%
% This script does not overwrite previous analyses.

clear; clc; close all;
rng(7,'twister');

%% ============================= CONFIG =============================
cfg = struct();

cfg.rootDir = '/Users/ghazal/Desktop/Article2/Analysis';
cfg.articleRoot = '/Users/ghazal/Desktop/Article2';

% The raw recordings in this project are primarily MAT files, not EDF.
% The first existing Subjects folder is used.
cfg.rawRootCandidates = { ...
    '/Users/ghazal/Desktop/Article2/Analysis/Subjects', ...
    '/Users/ghazal/Desktop/PhD thesis/IPM/Subjects', ...
    fullfile(cfg.articleRoot,'Subjects') ...
    };
cfg.rawRoot = firstExistingDir(cfg.rawRootCandidates);

cfg.outDir = fullfile(cfg.rootDir,'Result', ...
    'STEP10_FINAL_ARTICLE1_MATCHED_WINDOWS_N22');
if ~exist(cfg.outDir,'dir'); mkdir(cfg.outDir); end
cfg.figDir = fullfile(cfg.outDir,'figures');
if ~exist(cfg.figDir,'dir'); mkdir(cfg.figDir); end

% Existing trial-phase table generated by STEP09A2.
cfg.mergedTableCandidates = { ...
    fullfile(cfg.rootDir,'Result','STEP09A2_ConditionERP_Windows_N22', ...
        'STEP09A2_MergedTrialPhaseTable.csv'), ...
    fullfile(cfg.rootDir,'STEP09A2_ConditionERP_Windows_N22', ...
        'STEP09A2_MergedTrialPhaseTable.csv'), ...
    fullfile(cfg.rootDir,'STEP09A2_MergedTrialPhaseTable.csv') ...
    };

% Existing final spectral table. It is used only to recover/verify the final N=22 set.
cfg.finalFeatureCandidates = { ...
    fullfile(cfg.rootDir,'STEP03V3_TaskEEG_FinalQC', ...
        'TaskEEG_ChannelBand_SubjectFeatures_FINAL.csv'), ...
    fullfile(cfg.rootDir,'Result','STEP03V3_TaskEEG_FinalQC', ...
        'TaskEEG_ChannelBand_SubjectFeatures_FINAL.csv'), ...
    fullfile(cfg.rootDir,'TaskEEG_ChannelBand_SubjectFeatures_FINAL.csv') ...
    };

% Existing ERP subject-level table for direct cross-phase comparison.
cfg.erpCandidates = { ...
    fullfile(cfg.rootDir,'Result','STEP09A2_ConditionERP_Windows_N22', ...
        'STEP09A2_ERP_SubjectConditionComponents.csv'), ...
    fullfile(cfg.rootDir,'STEP09A2_ConditionERP_Windows_N22', ...
        'STEP09A2_ERP_SubjectConditionComponents.csv') ...
    };

cfg.finalSubjectsFallback = [ ...
    "s1";"s2";"s3";"s4";"s5";"s6";"s7";"s8";"s9"; ...
    "s11";"s12";"s13";"s14";"s15";"s16";"s17"; ...
    "s18";"s19";"s20";"s21";"s22";"s23" ...
    ];

cfg.targetPhases = ["stimulus","maintenance","retrieval"];
cfg.targetConditions = ["color","orientation","conjunction"];

cfg.fsDefault = 250;
cfg.maxChannels = 64;
% Primary phase windows, matched exactly to revised Article1.
cfg.primaryWindowSec = struct();
cfg.primaryWindowSec.stimulus    = 0.6;
cfg.primaryWindowSec.maintenance = 1.0;
cfg.primaryWindowSec.retrieval   = 0.6;

% Equal post-onset window used ONLY for direct cross-phase sensitivity.
cfg.sensitivityWindowSec = 0.6;

% Spectral extraction excludes the pre-event baseline interval.
cfg.usePreEventBaselineForSpectral = false;
cfg.useHamming = true;

cfg.bandNames = ["delta","theta","alpha","beta","gamma"];
cfg.bandRanges = [1 4; 4 8; 8 13; 13 30; 30 45];
cfg.logOffset = 1e-12;

cfg.minSubjectsForStats = 15;
cfg.alpha = 0.05;
cfg.saveWorkspace = true;
cfg.makeFigures = true;

cfg.roi = defineSpectralROIs();

%% =========================== FILE LOCATORS =========================
cfg.mergedFile = firstExistingFile(cfg.mergedTableCandidates);
if isempty(cfg.mergedFile)
    [f,p] = uigetfile('*.csv', ...
        'Select STEP09A2_MergedTrialPhaseTable.csv', cfg.rootDir);
    if isequal(f,0)
        error(['Merged trial-phase table not selected. Run STEP09A2 first, ' ...
            'or select STEP09A2_MergedTrialPhaseTable.csv.']);
    end
    cfg.mergedFile = fullfile(p,f);
end

cfg.finalFeatureFile = firstExistingFile(cfg.finalFeatureCandidates);
if isempty(cfg.finalFeatureFile)
    [f,p] = uigetfile('*.csv', ...
        'Select TaskEEG_ChannelBand_SubjectFeatures_FINAL.csv', cfg.rootDir);
    if isequal(f,0)
        error(['Final feature table is required to recover/verify the final N=22 set. ' ...
            'Select TaskEEG_ChannelBand_SubjectFeatures_FINAL.csv.']);
    end
    cfg.finalFeatureFile = fullfile(p,f);
end

cfg.erpFile = firstExistingFile(cfg.erpCandidates);

if isempty(cfg.rawRoot) || exist(cfg.rawRoot,'dir')~=7
    selectedRoot = uigetdir('/Users/ghazal/Desktop', ...
        'Select the IPM Subjects folder containing the raw MAT files');
    if isequal(selectedRoot,0)
        error('Raw Subjects folder was not selected.');
    end
    cfg.rawRoot = selectedRoot;
end

reportFile = fullfile(cfg.outDir, ...
    'STEP10_Final_Article1Matched_Report.txt');
if exist(reportFile,'file'); delete(reportFile); end
diary(reportFile);
diaryCleanup = onCleanup(@() diary('off')); %#ok<NASGU>

fprintf('============================================================\n');
fprintf('STEP10 FINAL ARTICLE1-MATCHED TASK-PERIOD ANALYSIS\n');
fprintf('Generated: %s\n',datestr(now));
fprintf('MATLAB: %s\n',version);
fprintf('Merged table: %s\n',cfg.mergedFile);
fprintf('Final feature table: %s\n',cfg.finalFeatureFile);
fprintf('Raw root: %s\n',cfg.rawRoot);
fprintf('Output: %s\n',cfg.outDir);
fprintf('Primary windows: stimulus 0-%.3f s | maintenance 0-%.3f s | retrieval 0-%.3f s\n', ...
    cfg.primaryWindowSec.stimulus,cfg.primaryWindowSec.maintenance,cfg.primaryWindowSec.retrieval);
fprintf('Direct-phase sensitivity window: 0-%.3f s for every phase\n',cfg.sensitivityWindowSec);
fprintf('Pre-event baseline included in spectral feature calculation: %d\n', ...
    cfg.usePreEventBaselineForSpectral);
fprintf('============================================================\n');

%% ======================= LOAD AND STANDARDIZE =====================
Mraw = readtable(cfg.mergedFile,'TextType','string', ...
    'VariableNamingRule','preserve');
M = standardizeMergedTable(Mraw);

Fraw = readtable(cfg.finalFeatureFile,'TextType','string', ...
    'VariableNamingRule','preserve');
F = standardizeFinalFeatureTable(Fraw);

if isempty(F)
    error('The selected final feature table could not be standardized.');
end

finalSubjects = unique(F.Subject,'stable');
finalSubjects = finalSubjects(strlength(finalSubjects)>0);
if numel(finalSubjects)~=22
    warning(['Final feature table contains %d unique subjects. ' ...
        'Using the fixed N=22 fallback list.'],numel(finalSubjects));
    finalSubjects = cfg.finalSubjectsFallback;
end
cfg.finalSubjects = finalSubjects(:);

fprintf('\nFinal subjects (%d): %s\n',numel(cfg.finalSubjects), ...
    strjoin(cellstr(cfg.finalSubjects),', '));

% Ensure raw EDF paths exist. Invalid/empty paths are remapped from rawRoot.
[M,rawMap] = repairRawPaths(M,cfg.rawRoot);
writetable(rawMap,fullfile(cfg.outDir,'STEP10_RawFileInventory.csv'));

keep = ismember(M.Subject,cfg.finalSubjects) & ...
       ismember(M.ConditionLabel,cfg.targetConditions) & ...
       ismember(M.PhaseLabel,cfg.targetPhases) & ...
       isfinite(M.PhaseStartSample) & M.PhaseStartSample>0 & ...
       strlength(M.RawEEGPath)>0;

M = M(keep,:);
M = unique(M(:,intersect( ...
    {'Subject','Run','Trial','ConditionLabel','PhaseLabel', ...
     'PhaseStartSample','RawEEGPath'}, ...
    M.Properties.VariableNames,'stable')),'rows','stable');

if isempty(M)
    error('No usable N=22 trial-phase rows remained after path repair.');
end

fprintf('Usable trial-phase rows: %d\n',height(M));
fprintf('Usable raw EDF files: %d\n',numel(unique(M.RawEEGPath)));
fprintf('Subjects represented: %d\n',numel(unique(M.Subject)));

writetable(M,fullfile(cfg.outDir, ...
    'STEP10_MergedTrialPhaseTable_N22_Repaired.csv'));

Tcoverage = makeCoverageTable(M,cfg);
writetable(Tcoverage,fullfile(cfg.outDir, ...
    'STEP10Q_TrialPhaseCoverage_BeforeExtraction.csv'));

%% ================= FINAL ARTICLE1-MATCHED EXTRACTION =================
% One fixed preprocessing/extraction path is used:
%   continuous 0.5-45 Hz band-pass, 50-Hz notch, average rereference,
%   event-locked post-onset segment only, Hamming window, FFT band power.
%
% Primary phase windows:
%   stimulus    0-0.6 s
%   maintenance 0-1.0 s
%   retrieval   0-0.6 s
%
% Direct phase sensitivity:
%   0-0.6 s for all three phases.

primaryMode = "article1_primary";
sensitivityMode = "equal0600_sensitivity";

fprintf('\n============================================================\n');
fprintf('EXTRACTING PRIMARY ARTICLE1-MATCHED WINDOWS\n');
fprintf('============================================================\n');

[TchanPrimary,TlogPrimary] = extractSubjectSpectralFeaturesFinal( ...
    M,cfg,primaryMode);

writetable(TchanPrimary,fullfile(cfg.outDir, ...
    'STEP10A_Article1Matched_SubjectChannelFeatures_N22.csv'));
writetable(TlogPrimary,fullfile(cfg.outDir, ...
    'STEP10A_Article1Matched_ReadLog.csv'));

fprintf('\n============================================================\n');
fprintf('EXTRACTING EQUAL 0-0.6 s DIRECT-PHASE SENSITIVITY WINDOWS\n');
fprintf('============================================================\n');

[TchanSensitivity,TlogSensitivity] = extractSubjectSpectralFeaturesFinal( ...
    M,cfg,sensitivityMode);

writetable(TchanSensitivity,fullfile(cfg.outDir, ...
    'STEP10S_Equal0600_SubjectChannelFeatures_N22.csv'));
writetable(TlogSensitivity,fullfile(cfg.outDir, ...
    'STEP10S_Equal0600_ReadLog.csv'));

%% ========================== RETENTION QC ===========================
TretPrimary = extractionRetentionSummary(TchanPrimary,cfg,primaryMode);
TretSens = extractionRetentionSummary(TchanSensitivity,cfg,sensitivityMode);

writetable(TretPrimary,fullfile(cfg.outDir, ...
    'STEP10Q_Primary_PhaseRetentionSummary.csv'));
writetable(TretSens,fullfile(cfg.outDir, ...
    'STEP10Q_Sensitivity_PhaseRetentionSummary.csv'));

fprintf('\n================ PRIMARY RETENTION =================\n');
disp(TretPrimary);
fprintf('\n=============== SENSITIVITY RETENTION ==============\n');
disp(TretSens);

%% ======================= PRIMARY ROI TABLE =========================
fprintf('\nBuilding primary non-overlapping scalp ROI features...\n');
Tchan = TchanPrimary;
Tchan.ROI = strings(height(Tchan),1);
for i=1:height(Tchan)
    Tchan.ROI(i) = channelToROI(Tchan.ChannelName(i),cfg.roi);
end

validROI = Tchan.ROI~="other";
if any(~validROI)
    warning('%d primary channel-feature rows could not be mapped to a spectral ROI.', ...
        sum(~validROI));
end

roiKeys = {'Subject','ConditionLabel','PhaseLabel','Band','ROI'};
[G,Troi] = findgroups(Tchan(validROI,roiKeys));
Xroi = Tchan(validROI,:);

Troi.AbsPower = splitapply(@(x) median(x,'omitnan'),Xroi.AbsPower,G);
Troi.LogAbsPower = splitapply(@(x) median(x,'omitnan'),Xroi.LogAbsPower,G);
Troi.RelPower = splitapply(@(x) median(x,'omitnan'),Xroi.RelPower,G);
Troi.NChannels = splitapply(@(x) numel(unique(x)),Xroi.ChannelIndex,G);
Troi.NTrials = splitapply(@(x) max(x),Xroi.NTrials,G);
Troi.WindowStartMs = zeros(height(Troi),1);
Troi.WindowEndMs = arrayfun(@(i) phaseDurationSec(Troi.PhaseLabel(i),cfg,primaryMode)*1000, ...
    (1:height(Troi))');

writetable(Troi,fullfile(cfg.outDir, ...
    'STEP10A_Article1Matched_SubjectROIFeatures_N22.csv'));

%% ================= PRIMARY CONDITION STATISTICS ====================
TchanLong = makeLongFeatureTable(Tchan,'ChannelName',"channel");
TroiLong = makeLongFeatureTable(Troi,'ROI',"roi");

[TchanOmni,TchanPair] = conditionStats(TchanLong,cfg.minSubjectsForStats);
[TroiOmni,TroiPair] = conditionStats(TroiLong,cfg.minSubjectsForStats);

writetable(TchanOmni,fullfile(cfg.outDir, ...
    'STEP10B_Article1Matched_Channel_Omnibus.csv'));
writetable(TchanPair,fullfile(cfg.outDir, ...
    'STEP10B_Article1Matched_Channel_Pairwise.csv'));
writetable(TroiOmni,fullfile(cfg.outDir, ...
    'STEP10B_Article1Matched_ROI_Omnibus.csv'));
writetable(TroiPair,fullfile(cfg.outDir, ...
    'STEP10B_Article1Matched_ROI_Pairwise.csv'));

TphaseCountsPrimary = [phaseCountSummary(TchanOmni,"channel"); ...
                       phaseCountSummary(TroiOmni,"roi")];
writetable(TphaseCountsPrimary,fullfile(cfg.outDir, ...
    'STEP10B_Article1Matched_PhaseEffectCountSummary.csv'));

%% ================= PRIMARY FOCUSED SPECTRAL INDICES ================
TcompPrimary = buildFocusedIndices(Troi);
writetable(TcompPrimary,fullfile(cfg.outDir, ...
    'STEP10B_Article1Matched_FocusedIndices_SubjectConditionPhase.csv'));

%% ============== EQUAL-0.6 s SENSITIVITY ROI TABLE ==================
Tsens = TchanSensitivity;
Tsens.ROI = strings(height(Tsens),1);
for i=1:height(Tsens)
    Tsens.ROI(i) = channelToROI(Tsens.ChannelName(i),cfg.roi);
end

validROIs = Tsens.ROI~="other";
roiKeysS = {'Subject','ConditionLabel','PhaseLabel','Band','ROI'};
[Gs,TroiSens] = findgroups(Tsens(validROIs,roiKeysS));
Xs = Tsens(validROIs,:);

TroiSens.AbsPower = splitapply(@(x) median(x,'omitnan'),Xs.AbsPower,Gs);
TroiSens.LogAbsPower = splitapply(@(x) median(x,'omitnan'),Xs.LogAbsPower,Gs);
TroiSens.RelPower = splitapply(@(x) median(x,'omitnan'),Xs.RelPower,Gs);
TroiSens.NChannels = splitapply(@(x) numel(unique(x)),Xs.ChannelIndex,Gs);
TroiSens.NTrials = splitapply(@(x) max(x),Xs.NTrials,Gs);
TroiSens.WindowStartMs = zeros(height(TroiSens),1);
TroiSens.WindowEndMs = repmat(cfg.sensitivityWindowSec*1000,height(TroiSens),1);

writetable(TroiSens,fullfile(cfg.outDir, ...
    'STEP10S_Equal0600_SubjectROIFeatures_N22.csv'));

TchanSensLong = makeLongFeatureTable(Tsens,'ChannelName',"channel");
TroiSensLong = makeLongFeatureTable(TroiSens,'ROI',"roi");

[TchanSensOmni,TchanSensPair] = conditionStats(TchanSensLong,cfg.minSubjectsForStats);
[TroiSensOmni,TroiSensPair] = conditionStats(TroiSensLong,cfg.minSubjectsForStats);

writetable(TchanSensOmni,fullfile(cfg.outDir, ...
    'STEP10S_Equal0600_Channel_Omnibus.csv'));
writetable(TchanSensPair,fullfile(cfg.outDir, ...
    'STEP10S_Equal0600_Channel_Pairwise.csv'));
writetable(TroiSensOmni,fullfile(cfg.outDir, ...
    'STEP10S_Equal0600_ROI_Omnibus.csv'));
writetable(TroiSensPair,fullfile(cfg.outDir, ...
    'STEP10S_Equal0600_ROI_Pairwise.csv'));

TphaseCounts = [phaseCountSummary(TchanSensOmni,"channel"); ...
                phaseCountSummary(TroiSensOmni,"roi")];
writetable(TphaseCounts,fullfile(cfg.outDir, ...
    'STEP10S_Equal0600_PhaseEffectCountSummary.csv'));

%% ============= DIRECT PHASE: EQUAL-0.6 s SPECTRAL ONLY ============
% IMPORTANT: direct phase magnitude comparisons are performed ONLY on the
% equal 0-0.6 s sensitivity branch, not on the unequal primary windows.

TchanMag = conditionEffectMagnitude(TchanSensLong);
TroiMag = conditionEffectMagnitude(TroiSensLong);

[TchanPhaseOmni,TchanPhasePair] = directPhaseStats( ...
    TchanMag,cfg.minSubjectsForStats,false);
[TroiPhaseOmni,TroiPhasePair] = directPhaseStats( ...
    TroiMag,cfg.minSubjectsForStats,false);

writetable(TchanMag,fullfile(cfg.outDir, ...
    'STEP10S_Channel_ConditionEffectMagnitude.csv'));
writetable(TroiMag,fullfile(cfg.outDir, ...
    'STEP10S_ROI_ConditionEffectMagnitude.csv'));
writetable(TchanPhaseOmni,fullfile(cfg.outDir, ...
    'STEP10S_Channel_DirectPhase_Omnibus.csv'));
writetable(TchanPhasePair,fullfile(cfg.outDir, ...
    'STEP10S_Channel_DirectPhase_Pairwise.csv'));
writetable(TroiPhaseOmni,fullfile(cfg.outDir, ...
    'STEP10S_ROI_DirectPhase_Omnibus.csv'));
writetable(TroiPhasePair,fullfile(cfg.outDir, ...
    'STEP10S_ROI_DirectPhase_Pairwise.csv'));

%% ============ FOCUSED INDICES: EQUAL-0.6 s DIRECT PHASE ============
Tcomp = buildFocusedIndices(TroiSens);
TcompMag = conditionEffectMagnitude(Tcomp);

[TcompPhaseOmni,TcompPhasePair] = directPhaseStats( ...
    TcompMag,cfg.minSubjectsForStats,true);

writetable(Tcomp,fullfile(cfg.outDir, ...
    'STEP10S_FocusedIndices_SubjectConditionPhase.csv'));
writetable(TcompMag,fullfile(cfg.outDir, ...
    'STEP10S_FocusedIndices_ConditionEffectMagnitude.csv'));
writetable(TcompPhaseOmni,fullfile(cfg.outDir, ...
    'STEP10S_FocusedIndices_DirectPhase_Omnibus.csv'));
writetable(TcompPhasePair,fullfile(cfg.outDir, ...
    'STEP10S_FocusedIndices_DirectPhase_Pairwise.csv'));

Tdir = buildDirectionalContrasts(Tcomp);
[TdirPhaseOmni,TdirPhasePair] = directPhaseStats( ...
    Tdir,cfg.minSubjectsForStats,true);

writetable(Tdir,fullfile(cfg.outDir, ...
    'STEP10S_FocusedIndices_DirectionalContrasts.csv'));
writetable(TdirPhaseOmni,fullfile(cfg.outDir, ...
    'STEP10S_FocusedIndices_DirectionalPhase_Omnibus.csv'));
writetable(TdirPhasePair,fullfile(cfg.outDir, ...
    'STEP10S_FocusedIndices_DirectionalPhase_Pairwise.csv'));

%% ====================== ERP DIRECT PHASE TEST ======================
TerpLong = table();
TerpMag = table();
TerpPhaseOmni = table();
TerpPhasePair = table();

if ~isempty(cfg.erpFile) && exist(cfg.erpFile,'file')==2
    fprintf('\nERP table: %s\n',cfg.erpFile);
    Eraw = readtable(cfg.erpFile,'TextType','string', ...
        'VariableNamingRule','preserve');
    TerpLong = standardizeERPTable(Eraw,cfg.finalSubjects);

    if ~isempty(TerpLong)
        TerpMag = conditionEffectMagnitude(TerpLong);
        [TerpPhaseOmni,TerpPhasePair] = directPhaseStats( ...
            TerpMag,cfg.minSubjectsForStats,true);

        writetable(TerpLong,fullfile(cfg.outDir, ...
            'STEP10D_ERP_SubjectCondition_Standardized.csv'));
        writetable(TerpMag,fullfile(cfg.outDir, ...
            'STEP10D_ERP_ConditionEffectMagnitude.csv'));
        writetable(TerpPhaseOmni,fullfile(cfg.outDir, ...
            'STEP10D_ERP_DirectPhase_Omnibus.csv'));
        writetable(TerpPhasePair,fullfile(cfg.outDir, ...
            'STEP10D_ERP_DirectPhase_Pairwise.csv'));
    end
else
    warning(['STEP09A2 ERP subject table was not found. ' ...
        'Spectral primary + equal-0.6-s sensitivity analyses completed; ERP direct phase test skipped.']);
end

%% ============================= FIGURES =============================
if cfg.makeFigures
    try
        plotFocusedMagnitudes(TcompMag,cfg.figDir);
    catch ME
        warning('Focused-index figure failed: %s',ME.message);
    end

    try
        plotPhaseCounts(TphaseCounts,cfg.figDir);
    catch ME
        warning('Phase-count figure failed: %s',ME.message);
    end
end

%% ========================= DECISION SUMMARY ========================
TdirectSummary = [ ...
    directSummary(TchanPhaseOmni,"channel"); ...
    directSummary(TroiPhaseOmni,"roi"); ...
    directSummary(TcompPhaseOmni,"focused_index"); ...
    directSummary(TerpPhaseOmni,"erp") ...
    ];

Tdecision = manuscriptDecisionFinal( ...
    TphaseCounts,TcompPhaseOmni,TerpPhaseOmni);

writetable(TdirectSummary,fullfile(cfg.outDir, ...
    'STEP10E_DirectPhase_SupportSummary.csv'));
writetable(Tdecision,fullfile(cfg.outDir, ...
    'STEP10E_ManuscriptDecisionSummary.csv'));

if cfg.saveWorkspace
    save(fullfile(cfg.outDir, ...
        'STEP10_FINAL_ARTICLE1_MATCHED_WINDOWS_N22_Workspace.mat'), ...
        'cfg','M','F','rawMap','Tcoverage','TchanPrimary','TlogPrimary', ...
        'TchanSensitivity','TlogSensitivity','TretPrimary','TretSens', ...
        'Tchan','Troi','TchanOmni','TchanPair','TroiOmni','TroiPair', ...
        'TphaseCountsPrimary','TphaseCounts', ...
        'TchanMag','TroiMag','TchanPhaseOmni','TchanPhasePair', ...
        'TroiPhaseOmni','TroiPhasePair','Tcomp','TcompMag', ...
        'TcompPhaseOmni','TcompPhasePair','Tdir','TdirPhaseOmni', ...
        'TdirPhasePair','TerpLong','TerpMag','TerpPhaseOmni', ...
        'TerpPhasePair','TdirectSummary','Tdecision','-v7.3');
end

fprintf('\n============================================================\n');
fprintf('STEP10 COMPLETED\n');
fprintf('Primary windows: stimulus 0-0.6 s | maintenance 0-1.0 s | retrieval 0-0.6 s\n');
fprintf('Direct-phase sensitivity: equal 0-0.6 s post-onset for all phases\n');
fprintf('============================================================\n');
disp(TdirectSummary);
disp(Tdecision);
fprintf('Outputs saved in:\n%s\n',cfg.outDir);
fprintf('Report saved in:\n%s\n',reportFile);
diary off;

%% ========================================================================
%                               LOCAL FUNCTIONS
% ========================================================================

function p = firstExistingDir(candidates)
p='';
for i=1:numel(candidates)
    if exist(candidates{i},'dir')==7
        p=candidates{i};
        return;
    end
end
end

function p = firstExistingFile(candidates)
p='';
for i=1:numel(candidates)
    if exist(candidates{i},'file')==2
        p=candidates{i};
        return;
    end
end
end

function M = standardizeMergedTable(T)
M=table();

sc=findColumn(T,{'Subject','SubjectID','Subj','Participant'});
rc=findColumn(T,{'Run','RunID','RunLabel'});
tc=findColumn(T,{'Trial','TrialNum','TrialNumber','TrialID','TrialIndex'});
cc=findColumn(T,{'ConditionLabel','Condition','TaskCondition','Cond'});
pc=findColumn(T,{'PhaseLabel','Phase','MemoryPhase'});
oc=findColumn(T,{'PhaseStartSample','StartSample','SampleOnset', ...
    'EventSample','OnsetSample','Start'});
ec=findColumn(T,{'RawEEGPath','EDFPath','EDFFile','RawPath', ...
    'RawFile','EEGFile','FilePath','SourceFile'});

required={sc,cc,pc,oc};
if any(cellfun(@isempty,required))
    error(['Merged trial-phase table lacks required subject, condition, ' ...
        'phase, or phase-start columns.']);
end

M.Subject=normalizeSubject(T.(sc));
if isempty(rc)
    M.Run=repmat("",height(T),1);
else
    M.Run=normalizeRun(T.(rc));
end
if isempty(tc)
    M.Trial=string((1:height(T))');
else
    M.Trial=normalizeTrial(T.(tc));
end
M.ConditionLabel=normalizeCondition(T.(cc));
M.PhaseLabel=normalizePhase(T.(pc));
M.PhaseStartSample=toDouble(T.(oc));
if isempty(ec)
    M.RawEEGPath=repmat("",height(T),1);
else
    M.RawEEGPath=strtrim(string(T.(ec)));
end
end

function F = standardizeFinalFeatureTable(T)
F=table();

sc=findColumn(T,{'Subject','SubjectID','Subj','Participant'});
cc=findColumn(T,{'ConditionLabel','Condition','TaskCondition','Cond'});
pc=findColumn(T,{'PhaseLabel','Phase'});
bc=findColumn(T,{'Band','FrequencyBand','FreqBand'});
nc=findColumn(T,{'ChannelName','ChanName','Channel','Chan'});
ic=findColumn(T,{'ChannelIndex','ChanIndex','ChannelIdx','ChIndex'});
lc=findColumn(T,{'LogAbsPower','LogAbsolutePower','log_abs_power'});
rc=findColumn(T,{'RelPower','RelativePower','relative_power'});
ac=findColumn(T,{'AbsPower','AbsolutePower','absolute_power'});

if any(cellfun(@isempty,{sc,cc,pc,bc}))
    warning('Final feature table lacks required identifier columns.');
    return;
end

F.Subject=normalizeSubject(T.(sc));
F.ConditionLabel=normalizeCondition(T.(cc));
F.PhaseLabel=normalizePhase(T.(pc));
F.Band=lower(strtrim(string(T.(bc))));

if isempty(nc)
    if isempty(ic)
        warning('Final feature table has no channel name or index.');
        F=table();
        return;
    end
    F.ChannelIndex=toDouble(T.(ic));
    F.ChannelName="ch"+string(F.ChannelIndex);
else
    F.ChannelName=strtrim(string(T.(nc)));
    if isempty(ic)
        F.ChannelIndex=nan(height(T),1);
    else
        F.ChannelIndex=toDouble(T.(ic));
    end
end

if isempty(lc)
    F.LogAbsPower=nan(height(T),1);
else
    F.LogAbsPower=toDouble(T.(lc));
end
if isempty(rc)
    F.RelPower=nan(height(T),1);
else
    F.RelPower=toDouble(T.(rc));
end
if isempty(ac)
    F.AbsPower=nan(height(T),1);
else
    F.AbsPower=toDouble(T.(ac));
end

% Collapse any duplicate/run-level rows to the same subject-condition-phase
% feature unit used in this sensitivity analysis.
keys={'Subject','ConditionLabel','PhaseLabel','Band', ...
    'ChannelIndex','ChannelName'};
[G,K]=findgroups(F(:,keys));
Fc=K;
Fc.LogAbsPower=splitapply(@(x) median(x,'omitnan'),F.LogAbsPower,G);
Fc.RelPower=splitapply(@(x) median(x,'omitnan'),F.RelPower,G);
Fc.AbsPower=splitapply(@(x) median(x,'omitnan'),F.AbsPower,G);
F=Fc;
end

function [M,rawMap] = repairRawPaths(M,rawRoot)
% Repair stale absolute paths after the IPM folder has been moved.
%
% Priority:
%   1) retain an existing path;
%   2) preserve the old relative path below IPM/Subjects;
%   3) match the exact old filename inside the new Subjects root;
%   4) propagate a successfully matched path to other rows from the same
%      Subject x Run cell.
%
% This is essential because subject IDs such as s1 do not correspond to the
% participant-name folder names in the raw archive.

rawMap=buildRawFileMap(rawRoot);
if isempty(rawMap)
    error(['No MAT or EDF recording files were found under:\n%s\n' ...
        'The selected folder must be the Subjects folder containing ' ...
        'participant-name subfolders and task MAT files.'],rawRoot);
end

M.RawPathMatchMode=repmat("",height(M),1);
M.OriginalRawEEGPath=string(M.RawEEGPath);

for i=1:height(M)
    oldPath=strtrim(string(M.RawEEGPath(i)));

    if strlength(oldPath)>0 && exist(oldPath,'file')==2
        M.RawPathMatchMode(i)="existing_path";
        continue;
    end

    [newPath,mode]=relocateRawPath(oldPath,rawRoot,rawMap);
    if strlength(newPath)>0
        M.RawEEGPath(i)=newPath;
        M.RawPathMatchMode(i)=mode;
    else
        M.RawEEGPath(i)="";
        M.RawPathMatchMode(i)="unresolved_first_pass";
    end
end

% Second pass: propagate within Subject x Run after at least one row from
% that recording has been matched by its old filename.
keys=unique(M(:,{'Subject','Run'}),'rows','stable');
for k=1:height(keys)
    idx=M.Subject==keys.Subject(k) & M.Run==keys.Run(k);
    resolved=unique(M.RawEEGPath(idx & strlength(M.RawEEGPath)>0));
    resolved=resolved(strlength(resolved)>0);

    if numel(resolved)==1
        fill=idx & strlength(M.RawEEGPath)==0;
        M.RawEEGPath(fill)=resolved(1);
        M.RawPathMatchMode(fill)="propagated_subject_run";
    end
end

nResolved=sum(strlength(M.RawEEGPath)>0);
fprintf('\nRaw path repair: %d/%d trial-phase rows resolved.\n', ...
    nResolved,height(M));

modes=unique(M.RawPathMatchMode,'stable');
for i=1:numel(modes)
    fprintf('  %-32s %d\n',modes(i),sum(M.RawPathMatchMode==modes(i)));
end

if nResolved==0
    error(['The MAT files were found, but none could be linked to the ' ...
        'stale paths in the merged table. Inspect STEP10_RawFileInventory.csv.']);
end
end

function [newPath,mode] = relocateRawPath(oldPath,rawRoot,rawMap)
newPath="";
mode="";

if strlength(oldPath)==0 || ismissing(oldPath)
    return;
end

oldChar=char(oldPath);
oldNorm=strrep(oldChar,'\','/');
oldLower=lower(oldNorm);

% A) Preserve the relative path below IPM/Subjects.
marker='ipm/subjects/';
pos=strfind(oldLower,marker);
if ~isempty(pos)
    suffix=oldNorm(pos(end)+length(marker):end);
    parts=strsplit(suffix,'/');
    candidate=rawRoot;
    for j=1:numel(parts)
        if ~isempty(parts{j})
            candidate=fullfile(candidate,parts{j});
        end
    end
    if exist(candidate,'file')==2
        newPath=string(candidate);
        mode="relative_path_below_subjects";
        return;
    end
end

% B) Exact filename match anywhere below the new Subjects root.
[oldParent,name,ext]=fileparts(oldChar);
target=lower(string([name ext]));
idx=lower(rawMap.FileName)==target;

if any(idx)
    C=rawMap(idx,:);

    % Prefer the same parent-folder name when duplicate filenames exist.
    [~,oldParentName]=fileparts(oldParent);
    sameParent=strcmpi(C.ParentFolder,string(oldParentName));
    if any(sameParent)
        C=C(sameParent,:);
    end

    [~,ord]=sort(C.CandidateScore,'descend');
    C=C(ord,:);

    for j=1:height(C)
        if exist(C.RawEEGPath(j),'file')==2
            newPath=C.RawEEGPath(j);
            mode="exact_filename";
            return;
        end
    end
end

% C) Same filename stem, allowing extension differences.
idx=lower(rawMap.BaseName)==lower(string(name));
if any(idx)
    C=rawMap(idx,:);
    [~,ord]=sort(C.CandidateScore,'descend');
    C=C(ord,:);
    newPath=C.RawEEGPath(1);
    mode="filename_stem";
end
end

function R = buildRawFileMap(root)
patterns={'*.mat','*.MAT','*.edf','*.EDF'};
files={};

for p=1:numel(patterns)
    files=[files;recursiveFiles(root,patterns{p})]; %#ok<AGROW>
end
files=unique(files,'stable');

rows=cell(0,12);
for i=1:numel(files)
    f=files{i};
    [parent,base,ext]=fileparts(f);
    [~,parentName]=fileparts(parent);
    b=lower(string(base));
    e=lower(string(ext));

    isWorkspace=contains(b,'workspace');
    isRest=isRestingFilename(b);
    isDerived=contains(lower(string(f)), ...
        ["eeg_analysis_advanced","complete_analysis","document", ...
         "patient_","list_","results","output"]);

    score=0;
    if e==".mat"; score=score+4; end
    if e==".edf"; score=score+5; end
    if contains(b,'filtered'); score=score+3; end
    if ~isempty(regexp(char(b),'([0-9]{1,2})$','once'))
        score=score+3;
    end
    if isWorkspace; score=score-25; end
    if isRest; score=score-50; end
    if isDerived; score=score-8; end

    [eegLike,bestVar,bestSize,inspectNote]=inspectRawCandidate(f);
    if eegLike; score=score+40; else; score=score-15; end

    rows(end+1,:)={string(f),string([base ext]),string(base), ...
        string(ext),string(parentName),score,isWorkspace,isRest, ...
        isDerived,eegLike,bestVar,bestSize+"|"+inspectNote}; %#ok<AGROW>
end

if isempty(rows)
    R=table();
    return;
end

R=cell2table(rows,'VariableNames', ...
    {'RawEEGPath','FileName','BaseName','Extension','ParentFolder', ...
     'CandidateScore','IsWorkspace','IsRestingLike','IsDerivedLike', ...
     'EEGLike','BestVariable','Inspection'});
R=standardizeOutputTable(R);

[~,ia]=unique(R.RawEEGPath,'stable');
R=R(ia,:);
R=sortrows(R,{'CandidateScore','RawEEGPath'}, ...
    {'descend','ascend'});

try
    writetable(R,fullfile(root,'STEP10_RawFileInventory.csv'));
catch
end
end

function tf = isRestingFilename(b)
tokens=["rest","resting","eyeopen","eye_open","eye-open", ...
    "eye close","eyeclose","eye_close","eye-close"];
tf=false;
for k=1:numel(tokens)
    if contains(b,tokens(k))
        tf=true;
        return;
    end
end
if ~isempty(regexp(char(b),'(^|[_\-\s])eo($|[_\-\s])','once')) || ...
   ~isempty(regexp(char(b),'(^|[_\-\s])ec($|[_\-\s])','once'))
    tf=true;
end
end

function [tf,bestVar,bestSize,note] = inspectRawCandidate(fpath)
tf=false;
bestVar="";
bestSize="";
note="not_inspected";

[~,~,ext]=fileparts(fpath);
if strcmpi(ext,'.edf')
    tf=true;
    bestVar="EDF";
    bestSize="unknown";
    note="edf_candidate";
    return;
end

if ~strcmpi(ext,'.mat')
    return;
end

try
    info=whos('-file',fpath);
catch ME
    note="whos_failed:"+string(ME.message);
    return;
end

bestScore=-Inf;
for i=1:numel(info)
    sz=double(info(i).size);
    % Some unusual MAT variables can return empty or scalar size metadata.
    % Convert every case to a safe two-element size vector.
    if isempty(sz)
        sz=[0 0];
    elseif isscalar(sz)
        sz=[sz 1];
    else
        sz=sz(1:2);
    end
    a=sz(1); b=sz(2);
    small=min(a,b); large=max(a,b);
    nm=lower(string(info(i).name));
    cls=lower(string(info(i).class));
    score=-Inf;

    if any(cls==["double","single","int16","int32","uint16", ...
            "uint32","logical"])
        if small>=16 && small<=128 && large>=1000
            score=100+log10(max(large,1))*5;
            if any(small==[64 65 66]); score=score+30; end
            if contains(nm,["eeg","data","signal","filtered","x"])
                score=score+15;
            end
        end
    elseif any(cls==["table","timetable"])
        if b>=16 && b<=128 && a>=1000
            score=90+log10(max(a,1))*5;
            if contains(nm,["eeg","data","signal"])
                score=score+15;
            end
        end
    elseif cls=="struct" && contains(nm,["eeg","data","signal"])
        score=40;
    end

    if score>bestScore
        bestScore=score;
        bestVar=string(info(i).name);
        bestSize=string(a)+"x"+string(b);
    end
end

tf=isfinite(bestScore) && bestScore>=40;
if tf
    note="eeg_like_variable_found";
else
    note="no_obvious_eeg_matrix";
end
end

function files = recursiveFiles(root,pattern)
files={};
if exist(root,'dir')~=7; return; end
d=dir(root);
for i=1:numel(d)
    if d(i).isdir && ~ismember(d(i).name,{'.','..'})
        files=[files;recursiveFiles(fullfile(root,d(i).name),pattern)]; %#ok<AGROW>
    end
end
dd=dir(fullfile(root,pattern));
for i=1:numel(dd)
    files{end+1,1}=fullfile(dd(i).folder,dd(i).name); %#ok<AGROW>
end
end

function T = makeCoverageTable(M,cfg)
[G,K]=findgroups(M(:,{'Subject','Run','ConditionLabel','PhaseLabel'}));
T=K;
T.NRows=splitapply(@numel,M.PhaseStartSample,G);
T.NFiniteOnsets=splitapply(@(x) sum(isfinite(x)&x>0), ...
    M.PhaseStartSample,G);
T.PrimaryWindowDurationMs=arrayfun(@(i) ...
    phaseDurationSec(T.PhaseLabel(i),cfg,"article1_primary")*1000, ...
    (1:height(T))');
T.SensitivityWindowDurationMs=repmat( ...
    cfg.sensitivityWindowSec*1000,height(T),1);
T.PreEventBaselineIncluded(:)=cfg.usePreEventBaselineForSpectral;
end

function [Tsubj,Tlog] = extractSubjectSpectralFeaturesFinal(M,cfg,branch)
groups=unique(M(:,{'Subject','ConditionLabel','PhaseLabel'}), ...
    'rows','stable');
nG=height(groups);

absCells=cell(nG,1);
relCells=cell(nG,1);
for g=1:nG
    absCells{g}=cell(0,1);
    relCells{g}=cell(0,1);
end

labelsByGroup=cell(nG,1);
trialCounts=zeros(nG,1);
durationByGroup=nan(nG,1);
logRows=cell(0,7);

rawFiles=unique(M.RawEEGPath,'stable');
for ifile=1:numel(rawFiles)
    rawPath=rawFiles(ifile);
    fprintf('Reading %d/%d: %s\n',ifile,numel(rawFiles),rawPath);

    try
        [X,labels,fs]=readRawEEG(rawPath,cfg.fsDefault,cfg.maxChannels);

        % Match the revised Article1 preprocessing description.
        X=applyDocumentedPreprocessing(X,fs);

    catch ME
        warning('Read/preprocessing failed: %s',ME.message);
        logRows(end+1,:)={rawPath,false,string(ME.message), ...
            NaN,NaN,branch,0}; %#ok<AGROW>
        continue;
    end

    rows=M(M.RawEEGPath==rawPath,:);
    nExtracted=0;

    for r=1:height(rows)
        onset=round(rows.PhaseStartSample(r));
        durationSec=phaseDurationSec(rows.PhaseLabel(r),cfg,branch);
        nEpoch=round(durationSec*fs);

        e0=onset;
        e1=onset+nEpoch-1;

        if ~isfinite(onset) || e0<1 || e1>size(X,1) || e1<e0
            continue;
        end

        % IMPORTANT: no pre-event baseline interval is included in spectral
        % feature calculation. The event-locked post-onset segment alone is
        % used, matching the revised Article1 analysis description.
        seg=double(X(e0:e1,:));

        % Demean and linearly detrend each channel within the analyzed segment.
        for ch=1:size(seg,2)
            x=seg(:,ch);
            good=isfinite(x);
            if sum(good)<max(10,round(0.25*fs))
                seg(:,ch)=NaN;
                continue;
            end

            if any(~good)
                x(~good)=median(x(good));
            end

            x=x-mean(x,'omitnan');
            x=detrend(x,'linear');
            seg(:,ch)=x;
        end

        if cfg.useHamming
            seg=seg.*hammingLocal(size(seg,1));
        end

        [bp,rp]=bandPowerOriginalStyle(seg,fs,cfg.bandRanges);
        if ~any(isfinite(bp(:))); continue; end

        g=find(groups.Subject==rows.Subject(r) & ...
               groups.ConditionLabel==rows.ConditionLabel(r) & ...
               groups.PhaseLabel==rows.PhaseLabel(r),1);
        if isempty(g); continue; end

        absCells{g}{end+1,1}=bp; %#ok<AGROW>
        relCells{g}{end+1,1}=rp; %#ok<AGROW>
        labelsByGroup{g}=labels;
        trialCounts(g)=trialCounts(g)+1;
        durationByGroup(g)=durationSec;
        nExtracted=nExtracted+1;
    end

    logRows(end+1,:)={rawPath,true,"ok",size(X,1), ...
        size(X,2),branch,nExtracted}; %#ok<AGROW>
end

rowsOut=cell(0,14);
for g=1:nG
    if isempty(absCells{g}); continue; end

    A=cat(3,absCells{g}{:});
    R=cat(3,relCells{g}{:});
    medA=median(A,3,'omitnan');
    medR=median(R,3,'omitnan');

    % Natural log, consistent with the Article2 manuscript wording.
    medL=median(log(A+cfg.logOffset),3,'omitnan');

    labels=labelsByGroup{g};
    if isempty(labels)
        labels=default64Labels(size(medA,1));
    end

    for ch=1:size(medA,1)
        for ib=1:numel(cfg.bandNames)
            rowsOut(end+1,:)={groups.Subject(g), ...
                groups.ConditionLabel(g),groups.PhaseLabel(g), ...
                cfg.bandNames(ib),ch,string(labels{ch}), ...
                medA(ch,ib),medL(ch,ib),medR(ch,ib), ...
                trialCounts(g),branch,0,durationByGroup(g)*1000, ...
                durationByGroup(g)*1000}; %#ok<AGROW>
        end
    end
end

Tsubj=cell2table(rowsOut,'VariableNames', ...
    {'Subject','ConditionLabel','PhaseLabel','Band', ...
     'ChannelIndex','ChannelName','AbsPower','LogAbsPower', ...
     'RelPower','NTrials','ExtractionMode','WindowStartMs','WindowEndMs','EpochDurationMs'});

% WindowEndMs and EpochDurationMs are identical because WindowStartMs=0.
if ~isempty(Tsubj)
    Tsubj.WindowEndMs=Tsubj.EpochDurationMs;
end
Tsubj=standardizeOutputTable(Tsubj);

if isempty(logRows)
    Tlog=table();
else
    Tlog=cell2table(logRows,'VariableNames', ...
        {'RawEEGPath','ReadOK','Status','NSamples','NChannels', ...
         'ExtractionMode','NExtractedTrialPhases'});
    Tlog=standardizeOutputTable(Tlog);
end
end

function sec = phaseDurationSec(phase,cfg,branch)
phase=normalizePhase(phase);
phase=phase(1);

if branch=="equal0600_sensitivity"
    sec=cfg.sensitivityWindowSec;
    return;
end

switch char(phase)
    case 'stimulus'
        sec=cfg.primaryWindowSec.stimulus;
    case 'maintenance'
        sec=cfg.primaryWindowSec.maintenance;
    case 'retrieval'
        sec=cfg.primaryWindowSec.retrieval;
    otherwise
        sec=NaN;
end
end

function T = extractionRetentionSummary(Tchan,cfg,branch)
phases=["stimulus","maintenance","retrieval"];
rows=cell(0,5);

for i=1:numel(phases)
    S=Tchan(Tchan.PhaseLabel==phases(i),:);
    if isempty(S)
        nSubj=0;
        nCells=0;
        medianTrials=NaN;
    else
        nSubj=numel(unique(S.Subject));
        U=unique(S(:,{'Subject','ConditionLabel','PhaseLabel','NTrials'}),'rows');
        nCells=height(U);
        medianTrials=median(U.NTrials,'omitnan');
    end

    dur=phaseDurationSec(phases(i),cfg,branch);
    rows(end+1,:)={phases(i),nSubj,nCells,medianTrials,dur*1000}; %#ok<AGROW>
end

T=cell2table(rows,'VariableNames', ...
    {'PhaseLabel','NSubjects','NSubjectConditionCells','MedianTrialsPerCell','WindowDurationMs'});
end

function [X,labels,fs] = readRawEEG(rawPath,fsDefault,maxChannels)
rawPath=char(rawPath);
if exist(rawPath,'file')~=2
    error('File not found: %s',rawPath);
end

[~,~,ext]=fileparts(rawPath);

if strcmpi(ext,'.edf')
    [X,labels,fs]=readEDFEEG(rawPath,fsDefault);
elseif strcmpi(ext,'.mat')
    [X,labels,fs]=readMATEEG(rawPath,fsDefault);
else
    error('Unsupported raw EEG extension: %s',ext);
end

if isempty(X) || ~isnumeric(X) || ndims(X)~=2
    error('No usable two-dimensional EEG matrix was recovered.');
end

% Orient as samples x channels.
[a,b]=size(X);
if a<=128 && b>max(a,1000)
    X=X';
elseif b>128 && a<=128
    X=X';
elseif b<=128 && a>b
    % already samples x channels
elseif a<=128 && b>a
    X=X';
end

if size(X,2)<16
    error('Recovered matrix has only %d candidate channels.',size(X,2));
end

% Retain the first 64 EEG channels; a possible 65th trigger channel is not
% included in spectral analysis.
if size(X,2)>maxChannels
    X=X(:,1:maxChannels);
end

if isempty(labels) || numel(labels)<size(X,2)
    labels=default64Labels(size(X,2));
else
    labels=cellstr(string(labels(1:size(X,2))));
end

X=double(X);
end

function [X,labels,fs] = readEDFEEG(rawPath,fsDefault)
if exist('edfread','file')~=2
    error('edfread is unavailable in this MATLAB installation.');
end

info=[];
try; info=edfinfo(rawPath); catch; end
TT=edfread(rawPath);
X=tableLikeToMatrix(TT);
labels=TT.Properties.VariableNames;
fs=fsDefault;

if ~isempty(info)
    try; labels=cellstr(string(info.SignalLabels)); catch; end
    try
        dur=seconds(info.DataRecordDuration);
        fs0=double(info.NumSamples(1))/dur;
        if isfinite(fs0)&&fs0>0; fs=fs0; end
    catch
    end
end
end

function [X,labels,fs] = readMATEEG(rawPath,fsDefault)
X=[];
labels={};
fs=fsDefault;

try
    info=whos('-file',rawPath);
catch ME
    error('Cannot inspect MAT file: %s',ME.message);
end

% Recover scalar sampling-rate metadata when available.
rateNames=["fs","srate","samplingrate","samplerate","frequency"];
for i=1:numel(info)
    nm=lower(string(info(i).name));
    if any(nm==rateNames) && prod(info(i).size)==1 && ...
            any(strcmpi(info(i).class,{'double','single','int32','uint32'}))
        try
            S=load(rawPath,info(i).name);
            v=double(S.(info(i).name));
            if isfinite(v)&&v>0; fs=v; end
        catch
        end
    end
end

% Rank candidate variables without loading the full workspace.
scores=-Inf(numel(info),1);
for i=1:numel(info)
    sz=double(info(i).size);
    % Some unusual MAT variables can return empty or scalar size metadata.
    % Convert every case to a safe two-element size vector.
    if isempty(sz)
        sz=[0 0];
    elseif isscalar(sz)
        sz=[sz 1];
    else
        sz=sz(1:2);
    end
    a=sz(1); b=sz(2);
    small=min(a,b); large=max(a,b);
    nm=lower(string(info(i).name));
    cls=lower(string(info(i).class));

    if any(cls==["double","single","int16","int32","uint16", ...
            "uint32","logical"])
        if small>=16 && small<=128 && large>=1000
            scores(i)=100+log10(max(large,1))*5;
            if any(small==[64 65 66]); scores(i)=scores(i)+35; end
            if contains(nm,["eeg","data","signal","filtered"])
                scores(i)=scores(i)+20;
            end
        end
    elseif any(cls==["table","timetable"])
        if b>=16 && b<=128 && a>=1000
            scores(i)=90+log10(max(a,1))*5;
            if contains(nm,["eeg","data","signal"])
                scores(i)=scores(i)+20;
            end
        end
    elseif cls=="struct"
        if contains(nm,["eeg","data","signal","dataset"])
            scores(i)=50;
        end
    end
end

[sortedScores,ord]=sort(scores,'descend');
for k=1:numel(ord)
    if ~isfinite(sortedScores(k)); break; end
    nm=info(ord(k)).name;

    try
        S=load(rawPath,nm);
        value=S.(nm);
        [X0,labels0,fs0]=extractEEGValue(value,fs);

        if isUsableEEGMatrix(X0)
            X=X0;
            labels=labels0;
            if isfinite(fs0)&&fs0>0; fs=fs0; end
            break;
        end
    catch
    end
end

% Fallback: load likely named variables individually.
if isempty(X)
    fallbackNames={'EEG','eeg','data','Data','signal','signals','X','x'};
    available={info.name};
    for i=1:numel(fallbackNames)
        hit=find(strcmpi(available,fallbackNames{i}),1);
        if isempty(hit); continue; end
        try
            S=load(rawPath,available{hit});
            [X0,labels0,fs0]=extractEEGValue(S.(available{hit}),fs);
            if isUsableEEGMatrix(X0)
                X=X0; labels=labels0; fs=fs0;
                break;
            end
        catch
        end
    end
end

if isempty(X)
    error(['No EEG-like matrix was found in MAT file: %s. ' ...
        'Expected a matrix with approximately 64 channels and at least ' ...
        '1000 samples.'],rawPath);
end

% Recover channel labels from separate metadata variables if needed.
if isempty(labels)
    labelAliases=["chanlabels","channellabels","labels","channelnames"];
    for i=1:numel(info)
        nm=lower(regexprep(string(info(i).name),'[^a-z0-9]',''));
        if any(nm==labelAliases)
            try
                S=load(rawPath,info(i).name);
                labels=cellstr(string(S.(info(i).name)));
                break;
            catch
            end
        end
    end
end
end

function [X,labels,fs] = extractEEGValue(value,fsDefault)
X=[];
labels={};
fs=fsDefault;

if isnumeric(value) || islogical(value)
    if ismatrix(value)
        X=double(value);
    end
    return;
end

if istable(value) || istimetable(value)
    X=tableLikeToMatrix(value);
    try; labels=value.Properties.VariableNames; catch; end
    return;
end

if isstruct(value)
    % Sampling rate.
    rateFields={'srate','fs','samplingRate','SamplingRate','sampleRate'};
    for i=1:numel(rateFields)
        if isfield(value,rateFields{i})
            v=value.(rateFields{i});
            if isnumeric(v)&&isscalar(v)&&isfinite(v)&&v>0
                fs=double(v);
                break;
            end
        end
    end

    % Channel labels.
    if isfield(value,'chanlocs')
        try; labels={value.chanlocs.labels}; catch; end
    elseif isfield(value,'labels')
        try; labels=cellstr(string(value.labels)); catch; end
    elseif isfield(value,'chanLabels')
        try; labels=cellstr(string(value.chanLabels)); catch; end
    end

    dataFields={'data','Data','EEG','eeg','X','x','signal','signals'};
    for i=1:numel(dataFields)
        if isfield(value,dataFields{i})
            [X0,L0,fs0]=extractEEGValue(value.(dataFields{i}),fs);
            if isUsableEEGMatrix(X0)
                X=X0;
                if isempty(labels); labels=L0; end
                if isfinite(fs0)&&fs0>0; fs=fs0; end
                return;
            end
        end
    end
end
end

function tf = isUsableEEGMatrix(X)
tf=false;
if isempty(X)||~isnumeric(X)||~ismatrix(X);return;end
[a,b]=size(X);
small=min(a,b); large=max(a,b);
tf=small>=16 && small<=128 && large>=1000;
end

function X = tableLikeToMatrix(TT)
vars=TT.Properties.VariableNames;
cols=cell(0,1);

for i=1:numel(vars)
    x=TT.(vars{i});
    try
        if iscell(x)
            try
                x=vertcat(x{:});
            catch
                z=cellfun(@(v) v(:),x,'UniformOutput',false);
                x=vertcat(z{:});
            end
        elseif istable(x)||istimetable(x)
            x=table2array(x);
        end

        if isnumeric(x)||islogical(x)
            cols{end+1,1}=double(x(:)); %#ok<AGROW>
        end
    catch
    end
end

if isempty(cols)
    X=[];
    return;
end

L=min(cellfun(@numel,cols));
X=nan(L,numel(cols));
for i=1:numel(cols)
    X(:,i)=cols{i}(1:L);
end
end

function X = applyDocumentedPreprocessing(X,fs)
if exist('butter','file')~=2 || exist('filtfilt','file')~=2
    error(['Signal Processing Toolbox functions butter/filtfilt are ' ...
        'required for documented_preprocessing mode.']);
end

X=double(X);
for ch=1:size(X,2)
    bad=~isfinite(X(:,ch));
    if any(bad)
        good=X(~bad,ch);
        if isempty(good)
            X(:,ch)=0;
        else
            X(bad,ch)=median(good);
        end
    end
end

% Fourth-order 0.5-45 Hz zero-phase Butterworth band-pass.
[b,a]=butter(4,[0.5 45]/(fs/2),'bandpass');
X=filtfilt(b,a,X);

% 50-Hz notch implemented as a narrow 49-51 Hz stop band.
if fs/2>51
    [bn,an]=butter(2,[49 51]/(fs/2),'stop');
    X=filtfilt(bn,an,X);
end

% Average reference across retained channels.
X=X-mean(X,2,'omitnan');
end

function w = hammingLocal(n)
if n<=1
    w=ones(n,1);
else
    w=0.54-0.46*cos(2*pi*(0:n-1)'/(n-1));
end
end

function [bp,rp] = bandPowerOriginalStyle(seg,fs,bands)
% Matches the FFT logic used by build_phase_features/bandpower_fft:
% mean removal, nfft=nextpow2(n), one-sided spectrum, trapz integration.
seg=double(seg);
n=size(seg,1);
nCh=size(seg,2);
nB=size(bands,1);

bp=nan(nCh,nB);
for ch=1:nCh
    x=seg(:,ch);
    x=x-mean(x,'omitnan');
    x(~isfinite(x))=0;

    nfft=2^nextpow2(n);
    F=fft(x,nfft);
    P2=abs(F/nfft).^2;
    P1=P2(1:floor(nfft/2)+1);
    freq=fs*(0:floor(nfft/2))/nfft;

    for ib=1:nB
        idx=freq>=bands(ib,1) & freq<=bands(ib,2);
        if any(idx)
            bp(ch,ib)=trapz(freq(idx),P1(idx));
        end
    end
end

den=sum(bp,2,'omitnan');
rp=bp./den;
rp(~isfinite(rp))=NaN;
end

function Q = compareWithOriginalFeatures(Tnew,F,mode)
A=Tnew(ismember(Tnew.PhaseLabel,["stimulus","retrieval"]),:);
B=F(ismember(F.PhaseLabel,["stimulus","retrieval"]),:);

% Prefer channel index because some historical tables store labels as
% ch01/ch02 while the EDF reader returns electrode labels such as Fp1/Fz.
A.ChannelKey=makeChannelKey(A.ChannelIndex,A.ChannelName);
B.ChannelKey=makeChannelKey(B.ChannelIndex,B.ChannelName);

keys={'Subject','ConditionLabel','PhaseLabel','Band','ChannelKey'};

A=A(:,[keys,{'LogAbsPower','RelPower'}]);
B=B(:,[keys,{'LogAbsPower','RelPower'}]);

A.Properties.VariableNames(end-1:end)= ...
    {'NewLogAbs','NewRel'};
B.Properties.VariableNames(end-1:end)= ...
    {'OldLogAbs','OldRel'};

J=innerjoin(A,B,'Keys',keys);

[rLog,pLog,nLog]=spearmanSafe(J.NewLogAbs,J.OldLogAbs);
[rRel,pRel,nRel]=spearmanSafe(J.NewRel,J.OldRel);

Q=table(string(mode),height(J),nLog,rLog,pLog,nRel,rRel,pRel, ...
    'VariableNames',{'ExtractionMode','NMatchedRows', ...
     'NFiniteLogAbs','Spearman_LogAbs','P_LogAbs', ...
     'NFiniteRelative','Spearman_Relative','P_Relative'});
end

function key = makeChannelKey(index,name)
index=double(index(:));
name=string(name(:));
key=strings(numel(name),1);

for i=1:numel(name)
    if isfinite(index(i)) && index(i)>0
        key(i)="index_"+string(round(index(i)));
    else
        key(i)="label_"+lower(regexprep(name(i),'[^A-Za-z0-9]',''));
    end
end
end

function [rho,p,n] = spearmanSafe(x,y)
x=double(x(:)); y=double(y(:));
ok=isfinite(x)&isfinite(y);
x=x(ok); y=y(ok); n=numel(x);
rho=NaN; p=NaN;
if n<5; return; end
try
    [rho,p]=corr(x,y,'Type','Spearman','Rows','complete');
catch
    rx=tiedrank(x); ry=tiedrank(y);
    C=corrcoef(rx,ry);
    rho=C(1,2);
    if n>2 && abs(rho)<1
        t=rho*sqrt((n-2)/(1-rho^2));
        p=2*(1-tcdf(abs(t),n-2));
    end
end
end

function m = rowMeanFinite(X)
m=nan(size(X,1),1);
for i=1:size(X,1)
    v=X(i,isfinite(X(i,:)));
    if ~isempty(v); m(i)=mean(v); end
end
end

function roi = defineSpectralROIs()
roi=struct();
roi.frontal=["Fp1","Fpz","Fp2","AF7","AF3","AFz","AF4","AF8", ...
    "F7","F5","F3","F1","Fz","F2","F4","F6","F8"];
roi.frontocentral=["FT7","FC5","FC3","FC1","FCz","FC2", ...
    "FC4","FC6","FT8","FT10"];
roi.central=["C5","C3","C1","Cz","C2","C4","C6"];
roi.centroparietal=["TP9","TP7","CP5","CP3","CP1","CPz", ...
    "CP2","CP4","CP6","TP8","TP10"];
roi.parietal=["P7","P5","P3","P1","Pz","P2","P4","P6","P8"];
roi.parieto_occipital=["PO7","PO3","POz","PO4","PO8"];
roi.occipital=["O1","Oz","O2"];
roi.temporal=["T7","T8"];
roi.order=["frontal","frontocentral","central","centroparietal", ...
    "parietal","parieto_occipital","occipital","temporal"];
end

function r = channelToROI(label,roi)
lab=upper(regexprep(string(label),'[^A-Za-z0-9]',''));
r="other";
for i=1:numel(roi.order)
    name=roi.order(i);
    members=upper(regexprep(roi.(char(name)),'[^A-Za-z0-9]',''));
    if any(lab==members)
        r=name;
        return;
    end
end
end

function labels = default64Labels(n)
base={'Fp1','Fpz','Fp2','AF7','AF3','AFz','AF4','AF8', ...
'F7','F5','F3','F1','Fz','F2','F4','F6','F8','FT7','FC5', ...
'FC3','FC1','FCz','FC2','FC4','FC6','FT8','T7','C5','C3', ...
'C1','Cz','C2','C4','C6','T8','TP7','CP5','CP3','CP1','CPz', ...
'CP2','CP4','CP6','TP8','P7','P5','P3','P1','Pz','P2','P4', ...
'P6','P8','PO7','PO3','POz','PO4','PO8','O1','Oz','O2','Iz', ...
'M1','M2'};
if n<=numel(base)
    labels=base(1:n);
else
    labels=cell(1,n);
    for i=1:n; labels{i}=sprintf('Ch%d',i); end
end
end

function Tlong = makeLongFeatureTable(T,featureCol,level)
base={'Subject','ConditionLabel','PhaseLabel','Band','NTrials'};

A=T(:,base);
A.FeatureName=string(T.(featureCol));
A.EEGMetric=repmat("log_absolute_power",height(T),1);
A.FeatureValue=T.LogAbsPower;
A.AnalysisLevel=repmat(string(level),height(T),1);

R=T(:,base);
R.FeatureName=string(T.(featureCol));
R.EEGMetric=repmat("relative_power",height(T),1);
R.FeatureValue=T.RelPower;
R.AnalysisLevel=repmat(string(level),height(T),1);

Tlong=[A;R];
end

function [Tomni,Tpair] = conditionStats(T,minN)
metrics=unique(T.EEGMetric,'stable');
phases=["stimulus","maintenance","retrieval"];
bands=unique(T.Band,'stable');
features=unique(T.FeatureName,'stable');
conds=["color","orientation","conjunction"];
pairs={1,2,"color_vs_orientation"; ...
       1,3,"color_vs_conjunction"; ...
       2,3,"orientation_vs_conjunction"};

orows=cell(0,14);
prows=cell(0,14);

for im=1:numel(metrics)
for ip=1:numel(phases)
for ib=1:numel(bands)
for jf=1:numel(features)
    S=T(T.EEGMetric==metrics(im) & T.PhaseLabel==phases(ip) & ...
        T.Band==bands(ib) & T.FeatureName==features(jf),:);

    [X,subj]=wideConditions(S);
    ok=all(isfinite(X),2);
    X=X(ok,:); subj=subj(ok);
    n=size(X,1);
    if n<minN; continue; end

    [pF,chi2,W]=friedmanStats(X);
    med=median(X,1,'omitnan');
    [~,mx]=max(med);

    orows(end+1,:)={string(S.AnalysisLevel(1)),metrics(im), ...
        phases(ip),bands(ib),features(jf),n,med(1),med(2),med(3), ...
        conds(mx),pF,chi2,W,strjoin(subj,'|')}; %#ok<AGROW>

    for k=1:3
        ia=pairs{k,1}; ibb=pairs{k,2};
        d=X(:,ia)-X(:,ibb);
        try; p=signrank(X(:,ia),X(:,ibb)); catch; p=NaN; end
        prows(end+1,:)={string(S.AnalysisLevel(1)),metrics(im), ...
            phases(ip),bands(ib),features(jf),string(pairs{k,3}),n, ...
            median(X(:,ia),'omitnan'),median(X(:,ibb),'omitnan'), ...
            median(d,'omitnan'),p,mean(d>0,'omitnan'), ...
            mean(d<0,'omitnan'),strjoin(subj,'|')}; %#ok<AGROW>
    end
end
end
end
end

if isempty(orows)
    Tomni=table();
else
    Tomni=cell2table(orows,'VariableNames', ...
        {'AnalysisLevel','EEGMetric','PhaseLabel','Band','FeatureName', ...
         'NSubjects','Median_color','Median_orientation', ...
         'Median_conjunction','MaxCondition','p_Friedman','ChiSquare', ...
         'KendallW','SubjectsUsed'});
    Tomni=standardizeOutputTable(Tomni);
    Tomni.q_FDR_metricFamily=nan(height(Tomni),1);
    for im=1:numel(metrics)
        idx=Tomni.EEGMetric==metrics(im);
        Tomni.q_FDR_metricFamily(idx)=bhFDR(Tomni.p_Friedman(idx));
    end
end

if isempty(prows)
    Tpair=table();
else
    Tpair=cell2table(prows,'VariableNames', ...
        {'AnalysisLevel','EEGMetric','PhaseLabel','Band','FeatureName', ...
         'Contrast','NSubjects','Median_A','Median_B', ...
         'MedianDiff_AminusB','p_Signrank','Proportion_AgtB', ...
         'Proportion_AltB','SubjectsUsed'});
    Tpair=standardizeOutputTable(Tpair);
    Tpair.q_FDR_metricFamily=nan(height(Tpair),1);
    Tpair.q_FDR_contrastFamily=nan(height(Tpair),1);
    contrasts=unique(Tpair.Contrast,'stable');
    for im=1:numel(metrics)
        idxM=Tpair.EEGMetric==metrics(im);
        Tpair.q_FDR_metricFamily(idxM)=bhFDR(Tpair.p_Signrank(idxM));
        for k=1:numel(contrasts)
            idx=idxM&Tpair.Contrast==contrasts(k);
            Tpair.q_FDR_contrastFamily(idx)=bhFDR(Tpair.p_Signrank(idx));
        end
    end
end
end

function [X,subjects] = wideConditions(S)
conds=["color","orientation","conjunction"];
subjects=unique(S.Subject,'stable');
X=nan(numel(subjects),3);
for i=1:numel(subjects)
    for c=1:3
        v=S.FeatureValue(S.Subject==subjects(i) & ...
            S.ConditionLabel==conds(c));
        if any(isfinite(v)); X(i,c)=median(v,'omitnan'); end
    end
end
end

function T = phaseCountSummary(O,level)
if isempty(O); T=table(); return; end
phases=["stimulus","maintenance","retrieval"];
metrics=unique(O.EEGMetric,'stable');
rows=cell(0,9);
for im=1:numel(metrics)
    for ip=1:3
        S=O(O.EEGMetric==metrics(im)&O.PhaseLabel==phases(ip),:);
        if isempty(S); continue; end
        sig=S.q_FDR_metricFamily<0.05;
        rows(end+1,:)={string(level),metrics(im),phases(ip), ...
            height(S),sum(sig,'omitnan'),median(S.KendallW,'omitnan'), ...
            max(S.KendallW,[],'omitnan'), ...
            median(S.p_Friedman,'omitnan'),mean(sig,'omitnan')}; %#ok<AGROW>
    end
end
T=cell2table(rows,'VariableNames', ...
    {'AnalysisLevel','EEGMetric','PhaseLabel','NTests', ...
     'NSignificantFDR','MedianKendallW','MaximumKendallW', ...
     'MedianP','ProportionSignificant'});
T=standardizeOutputTable(T);
end

function Tmag = conditionEffectMagnitude(T)
if isempty(T); Tmag=table(); return; end
keys=unique(T(:,{'Subject','EEGMetric','Band','FeatureName', ...
    'PhaseLabel','AnalysisLevel'}),'rows','stable');
conds=["color","orientation","conjunction"];
rows=cell(0,12);

for i=1:height(keys)
    idx=T.Subject==keys.Subject(i)&T.EEGMetric==keys.EEGMetric(i)& ...
        T.Band==keys.Band(i)&T.FeatureName==keys.FeatureName(i)& ...
        T.PhaseLabel==keys.PhaseLabel(i)& ...
        T.AnalysisLevel==keys.AnalysisLevel(i);

    v=nan(1,3);
    for c=1:3
        x=T.FeatureValue(idx&T.ConditionLabel==conds(c));
        if any(isfinite(x)); v(c)=median(x,'omitnan'); end
    end

    if all(isfinite(v))
        rows(end+1,:)={keys.Subject(i),keys.EEGMetric(i), ...
            keys.Band(i),keys.FeatureName(i),keys.PhaseLabel(i), ...
            keys.AnalysisLevel(i),v(1),v(2),v(3), ...
            max(v)-min(v),max(v),min(v)}; %#ok<AGROW>
    end
end

Tmag=cell2table(rows,'VariableNames', ...
    {'Subject','EEGMetric','Band','FeatureName','PhaseLabel', ...
     'AnalysisLevel','ColorValue','OrientationValue', ...
     'ConjunctionValue','EffectMagnitude', ...
     'MaximumConditionValue','MinimumConditionValue'});
Tmag=standardizeOutputTable(Tmag);
end

function [O,P] = directPhaseStats(T,minN,globalFamily)
if isempty(T); O=table();P=table();return;end
keys=unique(T(:,{'EEGMetric','Band','FeatureName','AnalysisLevel'}), ...
    'rows','stable');
phases=["stimulus","maintenance","retrieval"];
orows=cell(0,14);
prows=cell(0,12);

for i=1:height(keys)
    S=T(T.EEGMetric==keys.EEGMetric(i)&T.Band==keys.Band(i)& ...
        T.FeatureName==keys.FeatureName(i)& ...
        T.AnalysisLevel==keys.AnalysisLevel(i),:);
    subj=unique(S.Subject,'stable');
    X=nan(numel(subj),3);
    for is=1:numel(subj)
        for ip=1:3
            x=S.EffectMagnitude(S.Subject==subj(is)& ...
                S.PhaseLabel==phases(ip));
            if any(isfinite(x)); X(is,ip)=median(x,'omitnan'); end
        end
    end
    ok=all(isfinite(X),2);
    X=X(ok,:); subj=subj(ok);
    if size(X,1)<minN; continue; end

    [pF,chi2,W]=friedmanStats(X);
    med=median(X,1,'omitnan');
    dom=med(2)>med(1)&&med(2)>med(3);

    orows(end+1,:)={keys.AnalysisLevel(i),keys.EEGMetric(i), ...
        keys.Band(i),keys.FeatureName(i),size(X,1), ...
        med(1),med(2),med(3),pF,chi2,W,dom, ...
        strjoin(subj,'|'),false}; %#ok<AGROW>

    comp={2,1,"maintenance_vs_stimulus"; ...
          2,3,"maintenance_vs_retrieval"};
    for k=1:2
        d=X(:,comp{k,1})-X(:,comp{k,2});
        try
            p=signrank(X(:,comp{k,1}),X(:,comp{k,2}), ...
                'tail','right');
        catch
            p=NaN;
        end
        prows(end+1,:)={keys.AnalysisLevel(i),keys.EEGMetric(i), ...
            keys.Band(i),keys.FeatureName(i),string(comp{k,3}), ...
            size(X,1),median(X(:,comp{k,1}),'omitnan'), ...
            median(X(:,comp{k,2}),'omitnan'),median(d,'omitnan'), ...
            p,mean(d>0,'omitnan'),strjoin(subj,'|')}; %#ok<AGROW>
    end
end

if isempty(orows)
    O=table();
else
    O=cell2table(orows,'VariableNames', ...
        {'AnalysisLevel','EEGMetric','Band','FeatureName','NSubjects', ...
         'MedianEffect_Stimulus','MedianEffect_Maintenance', ...
         'MedianEffect_Retrieval','p_PhaseFriedman','ChiSquare', ...
         'KendallW','MaintenanceDominant','SubjectsUsed','StrongSupport'});
    O=standardizeOutputTable(O);
    O.q_PhaseFDR=nan(height(O),1);
end

if isempty(prows)
    P=table();
else
    P=cell2table(prows,'VariableNames', ...
        {'AnalysisLevel','EEGMetric','Band','FeatureName','Contrast', ...
         'NSubjects','Median_Maintenance','Median_Comparator', ...
         'MedianDifference','p_OneSidedSignrank', ...
         'Proportion_MaintenanceGreater','SubjectsUsed'});
    P=standardizeOutputTable(P);
    P.q_FDR=nan(height(P),1);
end

if isempty(O); return; end

if globalFamily
    O.q_PhaseFDR=bhFDR(O.p_PhaseFriedman);
    if ~isempty(P); P.q_FDR=bhFDR(P.p_OneSidedSignrank); end
else
    metrics=unique(O.EEGMetric,'stable');
    for im=1:numel(metrics)
        idx=O.EEGMetric==metrics(im);
        O.q_PhaseFDR(idx)=bhFDR(O.p_PhaseFriedman(idx));
        if ~isempty(P)
            idxp=P.EEGMetric==metrics(im);
            P.q_FDR(idxp)=bhFDR(P.p_OneSidedSignrank(idxp));
        end
    end
end

if ~isempty(P)
    P.SignificantFDR=P.q_FDR<0.05;
    for i=1:height(O)
        idx=P.EEGMetric==O.EEGMetric(i)&P.Band==O.Band(i)& ...
            P.FeatureName==O.FeatureName(i)& ...
            P.AnalysisLevel==O.AnalysisLevel(i);
        Q=P(idx,:);
        q1=Q.q_FDR(Q.Contrast=="maintenance_vs_stimulus");
        q2=Q.q_FDR(Q.Contrast=="maintenance_vs_retrieval");
        both=~isempty(q1)&&~isempty(q2)&&all(q1<0.05)&&all(q2<0.05);
        O.StrongSupport(i)=O.q_PhaseFDR(i)<0.05&& ...
            O.MaintenanceDominant(i)&&both;
    end
end
end

function [p,chi2,W] = friedmanStats(X)
p=NaN;chi2=NaN;W=NaN;
try
    [p,tbl]=friedman(X,1,'off');
    chi2=tbl{2,5};
    W=chi2/(size(X,1)*(size(X,2)-1));
catch
    n=size(X,1); k=size(X,2);
    R=zeros(size(X));
    for i=1:n; R(i,:)=tiedrank(X(i,:)); end
    Rj=sum(R,1);
    chi2=(12/(n*k*(k+1)))*sum(Rj.^2)-3*n*(k+1);
    p=1-chi2cdf(chi2,k-1);
    W=chi2/(n*(k-1));
end
end

function q = bhFDR(p)
p=double(p(:));q=nan(size(p));
ok=isfinite(p);pv=p(ok);
if isempty(pv);return;end
[ps,ord]=sort(pv);
m=numel(ps);
qs=ps.*m./(1:m)';
qs=flipud(cummin(flipud(qs)));
qs(qs>1)=1;
z=nan(m,1);z(ord)=qs;q(ok)=z;
end

function C = buildFocusedIndices(R)
keys=unique(R(:,{'Subject','ConditionLabel','PhaseLabel'}), ...
    'rows','stable');
rows=cell(0,8);

for i=1:height(keys)
    base=R.Subject==keys.Subject(i)& ...
        R.ConditionLabel==keys.ConditionLabel(i)& ...
        R.PhaseLabel==keys.PhaseLabel(i);

    x=R(base&R.Band=="alpha"& ...
        ismember(R.ROI,["parietal","parieto_occipital","occipital"]),:);
    v1=median(x.LogAbsPower,'omitnan');

    x=R(base&R.Band=="gamma"& ...
        ismember(R.ROI,["parietal","parieto_occipital"]),:);
    v2=median(x.RelPower,'omitnan');

    post=R(base&R.Band=="alpha"& ...
        ismember(R.ROI,["centroparietal","parietal", ...
        "parieto_occipital","occipital"]),:);
    ant=R(base&R.Band=="alpha"& ...
        ismember(R.ROI,["frontal","frontocentral"]),:);
    v3=median(post.RelPower,'omitnan')-median(ant.RelPower,'omitnan');

    rows(end+1,:)={keys.Subject(i),keys.ConditionLabel(i), ...
        keys.PhaseLabel(i),"alpha","posterior_alpha_log_power", ...
        "log_absolute_power",v1,"focused_index"}; %#ok<AGROW>
    rows(end+1,:)={keys.Subject(i),keys.ConditionLabel(i), ...
        keys.PhaseLabel(i),"gamma","posterior_gamma_relative_power", ...
        "relative_power",v2,"focused_index"}; %#ok<AGROW>
    rows(end+1,:)={keys.Subject(i),keys.ConditionLabel(i), ...
        keys.PhaseLabel(i),"alpha", ...
        "posterior_minus_anterior_alpha_relative_power", ...
        "relative_power",v3,"focused_index"}; %#ok<AGROW>
end

C=cell2table(rows,'VariableNames', ...
    {'Subject','ConditionLabel','PhaseLabel','Band','FeatureName', ...
     'EEGMetric','FeatureValue','AnalysisLevel'});
C=standardizeOutputTable(C);
C.NTrials=nan(height(C),1);
end

function D = buildDirectionalContrasts(C)
keys=unique(C(:,{'Subject','EEGMetric','Band','FeatureName', ...
    'PhaseLabel','AnalysisLevel'}),'rows','stable');
rows=cell(0,9);

for i=1:height(keys)
    S=C(C.Subject==keys.Subject(i)&C.EEGMetric==keys.EEGMetric(i)& ...
        C.Band==keys.Band(i)&C.FeatureName==keys.FeatureName(i)& ...
        C.PhaseLabel==keys.PhaseLabel(i),:);

    c=conditionValue(S,"color");
    o=conditionValue(S,"orientation");
    j=conditionValue(S,"conjunction");
    if ~all(isfinite([c o j]));continue;end

    if keys.FeatureName(i)=="posterior_gamma_relative_power"
        v=mean([o j])-c;
        definition="mean_orientation_conjunction_minus_color";
    else
        v=c-mean([o j]);
        definition="color_minus_mean_orientation_conjunction";
    end

    rows(end+1,:)={keys.Subject(i),keys.EEGMetric(i), ...
        keys.Band(i),keys.FeatureName(i),keys.PhaseLabel(i), ...
        keys.AnalysisLevel(i),v,definition,v}; %#ok<AGROW>
end

D=cell2table(rows,'VariableNames', ...
    {'Subject','EEGMetric','Band','FeatureName','PhaseLabel', ...
     'AnalysisLevel','DirectionalContrast','IndexDefinition', ...
     'EffectMagnitude'});
D=standardizeOutputTable(D);
end

function v = conditionValue(S,cond)
x=S.FeatureValue(S.ConditionLabel==cond);
if any(isfinite(x));v=median(x,'omitnan');else;v=NaN;end
end

function E = standardizeERPTable(T,subjects)
E=table();
sc=findColumn(T,{'Subject','SubjectID','Participant'});
cc=findColumn(T,{'ConditionLabel','Condition'});
pc=findColumn(T,{'PhaseLabel','Phase'});
kc=findColumn(T,{'Component','ERPComponent'});
rc=findColumn(T,{'ROI','Region'});
vc=findColumn(T,{'MedianMeanAmplitude','MeanAmplitude','Amplitude'});
if any(cellfun(@isempty,{sc,cc,pc,kc,rc,vc}));return;end

E.Subject=normalizeSubject(T.(sc));
E.ConditionLabel=normalizeCondition(T.(cc));
E.PhaseLabel=normalizePhase(T.(pc));
E.FeatureName=lower(strtrim(string(T.(kc))))+"__"+ ...
    lower(strtrim(string(T.(rc))));
E.Band=repmat("ERP",height(T),1);
E.EEGMetric=repmat("erp_mean_amplitude",height(T),1);
E.FeatureValue=toDouble(T.(vc));
E.AnalysisLevel=repmat("erp",height(T),1);
E.NTrials=nan(height(T),1);

keep=ismember(E.Subject,subjects)& ...
    ismember(E.ConditionLabel,["color","orientation","conjunction"])& ...
    ismember(E.PhaseLabel,["stimulus","maintenance","retrieval"])& ...
    isfinite(E.FeatureValue);
E=E(keep,:);
end

function plotFocusedMagnitudes(T,figDir)
if isempty(T);return;end
features=unique(T.FeatureName,'stable');
phases=["stimulus","maintenance","retrieval"];

for i=1:numel(features)
    S=T(T.FeatureName==features(i),:);
    subj=unique(S.Subject,'stable');
    X=nan(numel(subj),3);
    for is=1:numel(subj)
        for ip=1:3
            x=S.EffectMagnitude(S.Subject==subj(is)& ...
                S.PhaseLabel==phases(ip));
            if any(isfinite(x));X(is,ip)=median(x,'omitnan');end
        end
    end
    X=X(all(isfinite(X),2),:);
    if isempty(X);continue;end

    f=figure('Color','w','Position',[100 100 760 520]);
    hold on;
    for r=1:size(X,1)
        plot(1:3,X(r,:),'-o','Color',[.75 .75 .75], ...
            'LineWidth',.8,'MarkerSize',4);
    end
    med=median(X,1,'omitnan');
    plot(1:3,med,'-ok','LineWidth',3,'MarkerFaceColor','k');
    xticks(1:3);xticklabels({'Stimulus','Maintenance','Retrieval'});
    xlim([.7 3.3]);grid on;box off;
    ylabel('Condition-effect magnitude (max - min)');
    title(strrep(char(features(i)),'_',' '),'Interpreter','none');
    base=fullfile(figDir,['FocusedMagnitude_' char(features(i))]);
    saveas(f,[base '.png']);savefig(f,[base '.fig']);close(f);
end
end

function plotPhaseCounts(T,figDir)
if isempty(T);return;end
levels=unique(T.AnalysisLevel,'stable');
metrics=unique(T.EEGMetric,'stable');
phases=["stimulus","maintenance","retrieval"];

for il=1:numel(levels)
for im=1:numel(metrics)
    S=T(T.AnalysisLevel==levels(il)&T.EEGMetric==metrics(im),:);
    if isempty(S);continue;end
    y=zeros(1,3);
    for ip=1:3
        x=S.NSignificantFDR(S.PhaseLabel==phases(ip));
        if ~isempty(x);y(ip)=x(1);end
    end
    f=figure('Color','w','Position',[100 100 700 450]);
    bar(y);xticks(1:3);
    xticklabels({'Stimulus','Maintenance','Retrieval'});
    ylabel('Number of FDR-significant effects');
    title(sprintf('%s | %s | equal post-onset 0-600 ms sensitivity', ...
        levels(il),metrics(im)),'Interpreter','none');
    grid on;box off;
    base=fullfile(figDir,sprintf('EqualWindow_Counts_%s_%s', ...
        levels(il),metrics(im)));
    saveas(f,[base '.png']);savefig(f,[base '.fig']);close(f);
end
end
end

function S = directSummary(T,level)
if isempty(T)
    S=table(string(level),0,0,0,0,'VariableNames', ...
        {'AnalysisLevel','NTests','NPhaseFDRSignificant', ...
         'NMaintenanceDominant','NStrongSupport'});
else
    S=table(string(level),height(T), ...
        sum(T.q_PhaseFDR<0.05,'omitnan'), ...
        sum(T.MaintenanceDominant,'omitnan'), ...
        sum(T.StrongSupport,'omitnan'), ...
        'VariableNames',{'AnalysisLevel','NTests', ...
         'NPhaseFDRSignificant','NMaintenanceDominant', ...
         'NStrongSupport'});
end
end

function D = manuscriptDecisionFinal(counts,comp,erp)
nComp=0;nERP=0;
if ~isempty(comp);nComp=sum(comp.StrongSupport,'omitnan');end
if ~isempty(erp);nERP=sum(erp.StrongSupport,'omitnan');end

maintMost=false;
if ~isempty(counts)
    votes=false(0,1);
    levels=unique(counts.AnalysisLevel,'stable');
    metrics=unique(counts.EEGMetric,'stable');
    for i=1:numel(levels)
        for j=1:numel(metrics)
            S=counts(counts.AnalysisLevel==levels(i)& ...
                counts.EEGMetric==metrics(j),:);
            ns=phaseCountValue(S,"stimulus");
            nm=phaseCountValue(S,"maintenance");
            nr=phaseCountValue(S,"retrieval");
            if all(isfinite([ns nm nr]))
                votes(end+1,1)=nm>ns&&nm>nr; %#ok<AGROW>
            end
        end
    end
    if ~isempty(votes);maintMost=mean(votes)>=.5;end
end

if nComp>=1 && nERP>=1
    decision="strongest_supported";
    wording="were strongest during maintenance";
    rationale="Equal-0.6-s direct phase sensitivity showed corrected maintenance dominance in at least one focused spectral index and at least one ERP feature.";
elseif maintMost
    decision="predominantly_observed";
    wording="were predominantly observed during maintenance";
    rationale="Equal-0.6-s corrected condition effects were concentrated during maintenance, but direct strong support was not established in both focused spectral and ERP families.";
else
    decision="phase_specific_only";
    wording="showed phase-specific differences";
    rationale="The equal-0.6-s sensitivity and direct phase analyses did not support a general maintenance-dominance claim.";
end

D=table(decision,wording,rationale,nComp,nERP,maintMost, ...
    'VariableNames',{'Decision','RecommendedWording','Rationale', ...
    'NStrongFocusedIndices','NStrongERPFeatures', ...
    'MaintenanceHasMostSignificantEffects'});
end

function v = phaseCountValue(S,phase)
if isempty(S);v=NaN;return;end
x=S.NSignificantFDR(S.PhaseLabel==phase);
if isempty(x);v=NaN;else;v=x(1);end
end

function T = standardizeOutputTable(T)
if isempty(T); return; end

stringVars={'Subject','Run','Trial','ConditionLabel','PhaseLabel', ...
    'Band','ChannelName','ExtractionMode','RawEEGPath','Status', ...
    'InferenceReason','AnalysisLevel','EEGMetric','FeatureName', ...
    'MaxCondition','SubjectsUsed','Contrast','IndexDefinition', ...
    'FileName','BaseName','Extension','ParentFolder','BestVariable', ...
    'Inspection','OriginalRawEEGPath','RawPathMatchMode'};

for i=1:numel(stringVars)
    v=stringVars{i};
    if ismember(v,T.Properties.VariableNames)
        T.(v)=string(T.(v));
    end
end

logicalVars={'IsRestingLike','IsWorkspace','IsDerivedLike', ...
    'EEGLike','FileExists','ReadOK','MaintenanceDominant', ...
    'StrongSupport'};
for i=1:numel(logicalVars)
    v=logicalVars{i};
    if ismember(v,T.Properties.VariableNames) && iscell(T.(v))
        try
            T.(v)=logical(cell2mat(T.(v)));
        catch
        end
    end
end

numericVars={'Confidence','CandidateScore','NSamples','NChannels', ...
    'NExtractedTrialPhases', ...
    'ChannelIndex','AbsPower','LogAbsPower','RelPower','NTrials', ...
    'EpochDurationMs','NSubjects','Median_color','Median_orientation', ...
    'Median_conjunction','p_Friedman','ChiSquare','KendallW', ...
    'Median_A','Median_B','MedianDiff_AminusB','p_Signrank', ...
    'Proportion_AgtB','Proportion_AltB','NTests','NSignificantFDR', ...
    'MedianKendallW','MaximumKendallW','MedianP', ...
    'ProportionSignificant','ColorValue','OrientationValue', ...
    'ConjunctionValue','EffectMagnitude','MaximumConditionValue', ...
    'MinimumConditionValue','MedianEffect_Stimulus', ...
    'MedianEffect_Maintenance','MedianEffect_Retrieval', ...
    'p_PhaseFriedman','Median_Maintenance','Median_Comparator', ...
    'MedianDifference','p_OneSidedSignrank', ...
    'Proportion_MaintenanceGreater','FeatureValue', ...
    'DirectionalContrast'};

for i=1:numel(numericVars)
    v=numericVars{i};
    if ismember(v,T.Properties.VariableNames) && iscell(T.(v))
        try
            T.(v)=cell2mat(T.(v));
        catch
            T.(v)=str2double(string(T.(v)));
        end
    end
end
end

function col = findColumn(T,aliases)
col='';
vars=T.Properties.VariableNames;
clean=lower(regexprep(vars,'[^A-Za-z0-9]',''));
for i=1:numel(aliases)
    key=lower(regexprep(aliases{i},'[^A-Za-z0-9]',''));
    hit=find(strcmp(clean,key),1);
    if ~isempty(hit);col=vars{hit};return;end
end
for i=1:numel(aliases)
    key=lower(regexprep(aliases{i},'[^A-Za-z0-9]',''));
    hit=find(contains(clean,key),1);
    if ~isempty(hit);col=vars{hit};return;end
end
end

function s = normalizeSubject(x)
raw=lower(strtrim(string(x)));s=strings(numel(raw),1);
for i=1:numel(raw)
    tok=regexp(raw(i),'s[_\-\s]*0*([0-9]{1,3})','tokens','once');
    if isempty(tok);tok=regexp(raw(i),'subject[_\-\s]*0*([0-9]{1,3})','tokens','once');end
    if isempty(tok);tok=regexp(raw(i),'^0*([0-9]{1,3})$','tokens','once');end
    if ~isempty(tok);s(i)="s"+string(str2double(tok{1}));else;s(i)=raw(i);end
end
end

function r = normalizeRun(x)
raw=lower(strtrim(string(x)));r=strings(numel(raw),1);
for i=1:numel(raw)
    tok=regexp(raw(i),'run[_\-\s]*0*([0-9]{1,2})','tokens','once');
    if isempty(tok);tok=regexp(raw(i),'^0*([0-9]{1,2})$','tokens','once');end
    if ~isempty(tok);r(i)="run"+string(str2double(tok{1}));else;r(i)=raw(i);end
end
end

function t = normalizeTrial(x)
raw=strtrim(string(x));t=strings(numel(raw),1);
for i=1:numel(raw)
    v=str2double(raw(i));
    if isfinite(v);t(i)=string(round(v));else;t(i)=raw(i);end
end
end

function c = normalizeCondition(x)
s=lower(strtrim(string(x)));c=strings(numel(s),1);
for i=1:numel(s)
    if any(s(i)==["1","color","color_only","color-only","coloronly","c"])
        c(i)="color";
    elseif any(s(i)==["2","orientation","ori","orientation_only", ...
            "orientation-only","orientationonly","o"])
        c(i)="orientation";
    elseif any(s(i)==["3","conjunction","conj","binding"])
        c(i)="conjunction";
    else
        c(i)=s(i);
    end
end
end

function p = normalizePhase(x)
s=lower(strtrim(string(x)));p=strings(numel(s),1);
for i=1:numel(s)
    if contains(s(i),'stim');p(i)="stimulus";
    elseif contains(s(i),'maint')||contains(s(i),'delay')
        p(i)="maintenance";
    elseif contains(s(i),'retr')||contains(s(i),'probe')|| ...
            contains(s(i),'test')
        p(i)="retrieval";
    else;p(i)=s(i);
    end
end
end

function x = toDouble(v)
if isnumeric(v)||islogical(v)
    x=double(v(:));
else
    x=str2double(string(v(:)));
end
end
